### ISSUE TITLE
Error if I request CoinName having 2 Words

### ISSUE THREAD

**Issue by dante1989** [stepkillah/CoinMarketCalApi#1]
When i Call Request 
var result = await client.Events(new EventsRequest() { Coins = new List<string>() { "bitcoin", "ripple"} });
It is OK
But 2 words like
var result = await client.Events(new EventsRequest() { Coins = new List<string>() { "bitcoin cash"} });
I got error, maybe it not work with Coin name having 2 words
Could You help me to fix that?

**Comment by stepkillah** [comment]
@dante1989 Hello, are "bitcoin cash" is an Id for Bitcoin Cash?
You should use Id's returned by `Coins` method.

**Comment by dante1989** [comment]
Yes, I use Coins method. It also return "Bitcoin Cash"
After that, i tried: var result = await client.Events(new EventsRequest() { Coins = new List() { "bitcoin cash"} });
I got error

**Comment by stepkillah** [comment]
@dante1989 I checked - the ID of the bitcoin cash is "bitcoin-cash", not "Bitcoin Cash". Please, use Id property of Coin model

**Comment by dante1989** [comment]
Thank you so much :D
